#!/bin/sh

# http://concourse.ci/implementing-resources.html#resource-check

set -e

# parse incoming config data
payload=`cat`

# export for `aws` cli
AWS_ACCESS_KEY_ID=$(echo "$payload" | jq -r '.source.access_key_id // empty')
AWS_SECRET_ACCESS_KEY=$(echo "$payload" | jq -r '.source.secret_access_key // empty')
AWS_DEFAULT_REGION=$(echo "$payload" | jq -r '.source.region // empty')
AWS_DEFAULT_REPOSITORY=$(echo "$payload" | jq -r '.source.repository // empty')

# Due to precedence rules, must be unset to support AWS IAM Roles.
if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
  export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
fi

# Export AWS_DEFAULT_REGION if set
[ -n "$AWS_DEFAULT_REGION" ] && export AWS_DEFAULT_REGION

# Consider the most recent LastModified timestamp as the most recent version.
timestamps=$(aws ecr describe-images --repository-name sms-gateway --query 'sort_by(imageDetails,& imagePushedAt)[-1]')
last_date="$(echo $timestamps | jq -r '.imagePushedAt' | cut -d'T' -f1)"
# echo "$timestamps"
echo "$last_date"

# echo "- - - - - - - - - - - - - -"
# echo "$payload"
# echo "- - - - - - - - - - - - - -"
